# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
