# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0002_property_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='visitor_name',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_system.Owner'),
        ),
    ]
