# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.owner')),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.property')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('visitor_name', models.CharField(max_length=30)),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.property')),
            ],
        ),
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.TextField()),
                ('pref_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.visitor'),
        ),
        migrations.AddField(
            model_name='rented',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.visitor'),
        ),
    ]
