# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='prop_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='owner',
            name='num_properties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rented',
            name='rent_to_be_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rented',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Owner'),
        ),
        migrations.AlterField(
            model_name='rented',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Property'),
        ),
        migrations.AlterField(
            model_name='rented',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Visitor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Visitor'),
        ),
    ]
